- name: Logstash repo key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Configure Logstash repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install packages
  yum:
    name: logstash
    state: latest

- name: Set Logstash configuration
  replace:
    path: /etc/logstash/logstash.yml
    regexp: "# config.reload.automatic: false"
    replace: "config.reload.automatic: true"

- name: Configuration files for Logstash flows
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/

- service:
    name: logstash
    state: started
    enabled: yes
